### PR TITLE
Just some typos and a gitignore

### PR DESCRIPTION
**Pull request by dagelf**

### CODE REVIEW

**Comment by dagelf** [comment]
Did you make a runnable `train_gpt2.mojo` yet? Are there packages that mojo needs to install first? I couldn't find a commit that works, but didn't look very hard.

**Review by dorjeduck — APPROVED** [review]
thx

**Comment by dorjeduck** [comment]
just look harder :-)

It should work, what problems did you encounter? Did you follow the steps in the How to use section? The Mojo program itself does not need any extra packages but you need to install some python packages to run Andrej's python script to prepare the data set as mentioned ... Does llm.c run on you system?

**Comment by dagelf** [comment]
Just had to update mojo. Nothing worked!!! 100s of errors :smile:

**Comment by dorjeduck** [comment]
Thanks, stupid me. Added the required Mojo version to the Readme

**Pull request merged**
